### ISSUE TITLE
Product import - Configurable product - issue creating more than xx associated products at once, xx depending on the length of the skus

### ISSUE THREAD

**Issue by nbinnendijk** [Agence-DnD/PIMGento#110]
Hi,

Scenario: 
we try to import 116 simple products, all attached to the same group.
Pimgento creates all the 116 simple product - ok
Pimgento creates the configurable products -ok
Only the first 36 simple products are set as associated products of this configurable product - ko

Our current explanation:

when creating the temporary table, PIMgento set all the childs skus in one column, which max size is 256 chars. 
our skus are 6 chars long, plus one separator. 
36 * (6+1) = 252, so no more place for additional childs

**Comment by mtthb** [comment]
We were facing the same issue. Our workaround is change the following in ```Pimgento_Product_Model_Import```:
Around line 70:
```
$adapter = $this->getAdapter();
$adapter->query('SET SESSION group_concat_max_len = 1000000;');
```

Around line 142, replace ```$adapter->addColumn($this->getTable(), '_children',   'VARCHAR(255) NULL');``` by ```$adapter->addColumn($this->getTable(), '_children',   'TEXT NULL');```

Hope this helps, that did the trick for us.

**Comment by kvancappel** [comment]
Hi,

  sorry to use your topic, but could you confirm me. To make a configurable product in Akeneo, you created a new "variant-group", associated to it one or more axis (such as color for exemple), then choose what simple products associate to this configurable product please ? 
  I'm asking this question because when I export my variant_group from Akeneo, it look like it's OK (one  variant group is found). But, when I import this csv file into Magento by using PimGento, I don't find any new product in my Magento back-office.

  Is it normal please ? 

  Thank you
  Kévin

**Comment by magentix** [comment]
Configurable product associated with many simple products have been fixed in last commit.

@kvancappel Variant import just save in database the configurable axis (attributes). Products are created next with products import.
