### ISSUE TITLE
How to not import files attributes from Akeneo to Magento

### ISSUE THREAD

**Issue by kvancappel** [Agence-DnD/PIMGento#115]
Hi,

   I excluded the Akeneo codes of "file type" attributes in Magento > System > Configuration > Pimgento > Attributes.
  However, when I import my images , files entered in Akeneo are imported and appear in the back office Magento (Image tab) as you can see on the printscreen.

  How to permanently prevent the import of these files in Magento please ? (or export from Akeneo)

  Thank you
  Kévin V.
![problem_import_file](https://cloud.githubusercontent.com/assets/16002520/11779033/f3121422-a258-11e5-88b5-3cc7b31fc7c4.png)

**Comment by buttash** [comment]
From what I've seen of the code, it scans through all the files irrespective of attribute.  I've suggested a quick change to associate images, small_image and thumbnail in issue #111 .  This works in the assumption that the sub-folder name is the name of the attribute.  This code could be extended to just process files within a sub-folder that match required attributes...

**Comment by kvancappel** [comment]
Hi, 

  thank you, I will try it later.

  Kévin

**Comment by hostep** [comment]
Hi, we also run into this problem.

We have an attribute in Akeneo to upload pdf files, which is localizable. And we have 2 locales.
The product itself has only one image.

But after importing the product into Magento, we have 3 "images", one real image, and two pdf files which naturally give problems all over the place.

I believe the `Pimgento_Image_Helper_Data::getFiles` method needs to be rewritten completely, because it assumes way too much without looking at the contents of the csv files we feed it.
Issue #141 will also be fixed if this method is implemented in the "correct" way (whatever that is).

Thanks!

**Comment by DnD-Hellion** [comment]
Hi @kvancappel ,
Thank you for using PIMGento.

As I understand it, your are using the Image import.
This job will look into your media/import/files/ directory for product images.
It seems that your pdf files are also present in there, it may explain why they are linked to your product media gallery after importing your images.

Have you tried excluding those files from being exported by Akeneo in the media/import/files/ folder ?
If this is impossible, you may also rewrite PIMGento Image import to exclude pdf files, according to your needs.

Hope it helps, we look forward to reading you. ;)
Best regards,

**Comment by Dnd-Gimix** [comment]
Hi @kvancappel @hostep ,

We hope that that previous answer helped you to understand your problem.
As this issue is very old and has not been answered since a long time, I'll close it.

Feel free to open a new one if necessary ;-)
I wish you a good day !

Regards,
