### ISSUE TITLE
Akeneo single channel to Magento multi-store

### ISSUE THREAD

**Issue by jakemail** [Agence-DnD/PIMGento#118]
Hi @magentix,

I'm trying to use your extension for my Akeneo to Magento. We are using a single channel for our Magento multi-store (multiple languages).

So we have something like this (magento setup):
- store.com (en_US)
- store.be/nl (nl_BE)
- store.be/fr (fr_BE)
- store.co.uk (en_GB)
- store.fr (fr_FR)

In Akeneo we have 1 channel (Magento) and a single export contains a lot of localised fields like description-en_us, description-nl_BE, ...).

In your extension I'm only seeing a way to link a channel to a store view, is there currently a possibility to link languages to storeviews like I need? If not, maybe you can point me into the right direction on how I should develop this?

Thanks!

**Comment by nik736** [comment]
Have you found a solution here? I got the same problem.

**Comment by rskonieczka** [comment]
Please help me. I got the same problem.

**Comment by sammarcus** [comment]
@rskonieczka `Integrity constraint violation` means that there is a mismatch between the two tables — something does not exist in a table that relies on the next.


In your case, the value for column `product_id` on table `sklep_catalog_product_website` you are inserting doesn't exist on table `sklep_catalog_product_entity`. It's throwing an error because the values of column `product_id` on table `sklep_catalog_product_website` is dependent on the values of ID on table `sklep_catalog_product_entity`. 

I recommend breaking down the CSV you're trying to import and going line by line to see which item is cause the error specifically.

**Comment by magentix** [comment]
@rskonieczka: problem have recently been fixed.

@jakemail: In akeneo, attributes must be simply "localisable". So in export you will have:

attribute-fr_FR; attribute-en_US...

Pimgento will set data for all stores with fr_FR, en_US languages,

**Comment by avinashsamala** [comment]
hi 

how to use PImgento for multiple stores in magento 2.

thanks
