### ISSUE TITLE
Product Image Import: Default Magento Image?

### ISSUE THREAD

**Issue by nik736** [Agence-DnD/PIMGento#128]
Hi guys,

I have the problem that alle images get imported correctly but if I visit a product in the frontend it shows the default Magento image. And I need to click on the thumbnail for the product to become big. The default Magento image shouldn't show up at all. Why is it like that?

In the backend it looks like this:
![screen shot 2016-02-29 at 09 12 56](https://cloud.githubusercontent.com/assets/1334622/13388956/ab1dc50a-dec4-11e5-95fc-7c37eacb575b.png)

If I change the third column to the actual image and save and reimport things it is looking like the screenshot again. What do I need to change for it to be imported/setup correctly?

Thanks!!!

**Comment by buttash** [comment]
Hi Niklas
I’ve been looking into this area in order to allocate small_image, thumbnail and image to the correct attributes.  I’ve made a change to the code base which seems to fix - I plan to create a PR in due course.  Image/Model/Import.php at line 154:

if ($key === 0) {
    $data['image'] = $picture['name'];
    $data['small_image'] = $picture['name'];
    $data['thumbnail'] = $picture['name'];
}
// Allocate image to Magento attribute
$type = basename($picture['directory']);
if ($type == 'image' || $type == 'small_image' || $type == 'thumbnail') {
    $data[$type] = $picture['name'];
}
Not sure if this answers your issue...
Martin

**Comment by nik736** [comment]
Thanks, this doesn't help though. The problem is still there.

I don't understand why...

**Comment by DnD-Hellion** [comment]
@nik736 ,
Thank you for using PIMGento.
It seems you are using a custom image attribute.
Therefore, we would recommand you to develop a specific rewrite of the module, adapted to your needs, so PIMGento can take this attribute into account.

I mark this issue as closed.

Best Regards,
