### ISSUE TITLE
PIMGENTO

### ISSUE THREAD

**Issue by Noobsynoobs** [Agence-DnD/PIMGento#151]
Hi, 

I am trying to include multiple images per product without creating multiple image attributes, i.e by including image URLs in the same column separated by a '\'. Unfortunately this doesnt work in akeneo and I am forced to create multiple attributes of type image which is not what I want. Is there a way how PIMGENTO can take care of this like the above mentioned strategy in magento. I am trying to export the product data to magento from akeneo using Pimgento. 

All help is appreciated. 
Regards

**Comment by DnD-Hellion** [comment]
Hi @Noobsynoobs ,
Thank you for using PIMGento.
As it is an old proposition and has not been supported, we close this issue.
We recommand that you use the asset variations functionnality in order to set multiple images to your products :
https://help.akeneo.com/articles/work-with-assets.html
https://www.pimgento.com/docs/v1.0/configuration/assets_variation

Best regards,
