### ISSUE TITLE
Import Product : SKU have been duplicated

### ISSUE THREAD

**Issue by hungpq12** [Agence-DnD/PIMGento#17]
I'm created product with sku : test_123 in Magento.
Import module(Pimgento) created duplicated product with the same sku instead of updating existing one

**Comment by manh-nguyen** [comment]
Product are duplicated because they check the existing SKU in pimgento_code table. If sku is not found in this table, it will be marked as new product.
To solve this issue, need to write a sql command to update this table before each import time.

  INSERT IGNORE INTO `pimgento_code` (
	`import`,
	`code`,
	`entity_id`
) SELECT
	'product' AS `import`,
	`catalog_product_entity`.`sku` as `code`,
	`catalog_product_entity`.`entity_id`
FROM
	`catalog_product_entity`
WHERE `entity_type_id`='4'

**Comment by magentix** [comment]
Hello,

@manh-nguyen solution is right, You can use this request to sync product.
