### ISSUE TITLE
Variant group is imported without children

### ISSUE THREAD

**Issue by jeroenegbertzen** [Agence-DnD/PIMGento#189]
Hi,

I can import the variant and product csv file to create products, and it seems to be succesfull but no children are added to my configurable product. The configurable product also does not have a status. See image.

What am I missing? Hope someone can give me the golden advice!

See attached files I use. 

![catalog inventory products magento admin](https://cloud.githubusercontent.com/assets/26488974/24053236/af7e5bea-0b38-11e7-8df8-e3d821e8ceed.png)

[akeneo.zip](https://github.com/Agence-DnD/PIMGento/files/851206/akeneo.zip)

**Comment by magentix** [comment]
Hi,

This issue is about Pimgento 2, please add issue on PIMGento-2 repository: https://github.com/Agence-DnD/PIMGento-2

Pimgento build configurable products with variant according the "groups" column in product import. Can you check that column nammed **groups** in products import file is in **pimgento_assets** table for column **code**?
