### ISSUE TITLE
 how to get the csv file for families, product images and stocks?

### ISSUE THREAD

**Issue by manh-nguyen** [Agence-DnD/PIMGento#2]
Hey guys,

I wonder how do you guys get the csv file for families, product images and stocks?
PIM default doesn't support to export these information.

Please share how you do it.

Thanks guys & Cheers !
Manh

**Comment by christophednd** [comment]
I Manh,
You have to install DnD-MagentoConnectorBundle for Akeneo >=1.3 in order to generate appropriate CSV files for Magento : https://github.com/Agence-DnD/DnD-MagentoConnectorBundle
Stock file is not generated by Akeneo, but you can import with PIMGento your own CSV file with just 2 columns.

![capture d ecran 2015-04-17 a 08 27 06](https://cloud.githubusercontent.com/assets/7805028/7196989/93784d96-e4db-11e4-8f99-137faaa6a834.png)

Christophe

**Comment by manh-nguyen** [comment]
Thank you very much, Christophe!!!

**Comment by manh-nguyen** [comment]
hi @christophednd ,
Can you please send me the files as in demo https://www.youtube.com/watch?v=MpC01qVIVFA
- attribute.csv
- category.csv
- family.csv
- option.csv
- product.csv
- stock.csv

Actually, the import product is not working with us. We configured everything as the guide but no luck.
So i really want to see the csv file working for pimgento.

My email is manh@balanceinternet.com.au

Regards,
Manh
