### ISSUE TITLE
unable to load categories file into Magento used pimgento 10.2

### ISSUE THREAD

**Issue by maramkoteswar** [Agence-DnD/PIMGento#31]
While uploading categories file into magento,got  Notice : Undefined offset: 1 in 
Pimgento_Core_Model_Resource_Request.php on line no:393
 and its stopped loading categories. When we use previous versions of pimgento we never had this problem.

Please find the attached screenshot and file for your reference.

Thanks in advnace.

Regards,
Koteswar Maram
![dev_categories_error](https://cloud.githubusercontent.com/assets/7391942/7881507/6ad1feac-0621-11e5-8cb8-104e3319967e.JPG)
![pimgento_core_model_resource_request](https://cloud.githubusercontent.com/assets/7391942/7881508/6ad463fe-0621-11e5-95fa-80df6111fc3f.JPG)

**Comment by DnD-Mimosa** [comment]
Hi @maramkoteswar,

This error may come from your compilation which seems to be enable. Go to System > Tools > Compilation and try to recompile your Magento code.

Regards,
Florian.

**Comment by DnD-Mimosa** [comment]
@maramkoteswar,

You opened two same issues so can you answer the opened one please. Here is your answer :

As per mentioned above i have followed setp
Go to System > Tools > Compilation and recompiled my Magento code and restarted the apache but still i am getting the same above error.

Do you also have cache opcode like APC or memecache, in this case, you also have to refresh it.

Regards,
Florian.

**Comment by freakpol** [comment]
This is caused by two factors:
1.- Your database info in app/etc/local.xml contains something like <host>localhost</host>
2.- You have php configured too strict

I'm in favor of point 2, and for point 1, we I think extension should NOT assume it will contain the ":" char with the port.

The correct solution here will be either add an '@' at the beginning of the line (to suppress error) or to check if $connConfig->host contains ":".

**Comment by magentix** [comment]
Hello,

We have fixed this problem in the last version.
