### ISSUE TITLE
Why are you guys closing all user issues? 

### ISSUE THREAD

**Issue by linslin** [Agence-DnD/PIMGento#61]
Hey @magentix  could you explain why you are closing all the tickets from users here? PIMGento have a lot of problems. Instead of closing you should ask the users to make PIMGento stable (cause PIMGento is not stable and not compatible with Akeneo/Magento). If you respond, you should wait until the users Issue is fixed and he provided some feedback... 

### Those Tickets: 
https://github.com/Agence-DnD/PIMGento/issues/55
https://github.com/Agence-DnD/PIMGento/issues/54
https://github.com/Agence-DnD/PIMGento/issues/52
https://github.com/Agence-DnD/PIMGento/issues/51
https://github.com/Agence-DnD/PIMGento/issues/49
https://github.com/Agence-DnD/PIMGento/issues/48
https://github.com/Agence-DnD/PIMGento/issues/47
https://github.com/Agence-DnD/PIMGento/issues/46
https://github.com/Agence-DnD/PIMGento/issues/45
https://github.com/Agence-DnD/PIMGento/issues/44
https://github.com/Agence-DnD/PIMGento/issues/43
https://github.com/Agence-DnD/PIMGento/issues/42
https://github.com/Agence-DnD/PIMGento/issues/41
https://github.com/Agence-DnD/PIMGento/issues/38
etc.

Please explain yourself and that kind of "support".

**Comment by christophednd** [comment]
Hey @linslin !
thanks for using PIMGento and for your contribution, but i don’t understand your aggressivity for all this issues.

We try to answer these questions or problems based on the most critical of them and according to our internal calendar.

PIMGento is stable, works, but still in development to be "plug and play" for any kind of specific or exotic Magento / Akeneo configurations.
And at this point, sometime, inappropriate Magento / Akeneo self made developments or serveur configurations couldn’t work with it.

But i can confirm that PIMGento is compatible and works in Production for many users around the world with a lot of benefit ;)

Remember : PIMGento is Free !

We’ve released it on GitHub ("open source spirit") to help merchands and developers to connect Akeneo with Magento, better, faster and stronger ;)

The community can make evolve this connector by "Pull Request" if they have solution on a problem or if they propose an evolution, but not just by criticizing the support provided because PIMGento doesn’t works as you want for your project.

Many issues mentionned are closed because we brought a solution or a track to explore for a specific configuration or sometimes just because it is a "Merge Request" accepted from the community.

If you have any ways for improvement on the source code, you're welcome with a Pull request.

We'll keep moving on, to help you and the community around this initiative.

But please, stay cool and positive ;)

Christophe

**Comment by linslin** [comment]
Hey @christophednd,

thanks for your reply. I had/have a lot of problems with PIMGento:

- No full documentation, only Screenshots, a Youtube-Video and a github -> https://github.com/Agence-DnD/PIMGento#configuration-and-usage. All this does not explain how to use all features of PIMGento. There is no example for a CSV-Data import with/without configurable products, etc. Please see that point. This point is the main problem while implementing PIMGento. 
- If you you guys closing github issues without waiting for the user input and/or bring no feedback makes the users feel bad. There was no support answer for more than 2 month's before this closing "wave" on yesterday happened. Sorry, but what should you think if your support tickets will be closed before its cleared/tested/feedback. 
- The System we are creating is nothing abnormally. We talking about about 10k of Products with variants. All this is currently support by PIMGento. You see all the PIMGento problems I had in the issues I created. Instead of fixing or asking for reproduction to make PIMGento more stable, you are closing the most of the Tickets. I also read the installation guide ;).

I don't want to be chatty, sorry so, but I'am still afraid. Asking "why this closing wave happened" is nothing aggressiv.

> Many issues mentionned are closed because we brought a solution or a track to explore for a specific configuration or sometimes just because it is a "Merge Request" accepted from the community.

Some issues were closed without any feedback, all issues are closed without knowing its "cleared". No issues are waiting for user feedback. Maybe you fear there are more open issues than stars in this repository. So lets cancel this discussion. It was the first and last time I used this "software". 

Lin - out.
