### ISSUE TITLE
Re-open issue #44

### ISSUE THREAD

**Issue by mrafulfill** [Agence-DnD/PIMGento#69]
If attribute type in Akeneo is set to price, the attribute import will create a new attribute in Magento with type "text field". If a price attribute is manually created in Magento with attribute type price the import of prices will not succeed. The same issues applies to the native Magento attribute MSRP (manufacturer suggested retail price). Values for MSRP cannot be imported. This is probably related to the fact that only price and special price are hard coded.

![price hard coded](https://cloud.githubusercontent.com/assets/4086514/8731625/e9e1908e-2bf8-11e5-8168-66f9c869df54.PNG)

This issue should not be closed again without solving at least the native Mageto price attributes, therefore the native MSRP price attribute should be included in the code snippet above.

**Comment by linslin** [comment]
:+1:

**Comment by magentix** [comment]
Hi,

For prices, you must match your Pimgento attribute (ex: my_price) with Magento price attribute (price) in Pimgento configuration.

Attributes are hard coded because column name for prices is specific compared to others attributes (we have currency in column name). Moreover, "price" and "special_price" are required in Magento.

**Comment by akkermanronald** [comment]
Hi Magentix. 

That's understood. It's fine for these attributes to be hard coded. But MSRP is also a native Magento attribute where currency and tax apply and are needed to calculate prices including or excluding tax.

It would be relatively straight forward to include msrp in your code (also hard coded) so these values can be in the CSV including the currency element? 

We have already implented this ourselves in a fork and have emailed you this solution for consideration. However, we find it a bit hard to code the configurable prices part, otherwise we would be happy to make a pull request. 

Regards
Ronald

**Comment by magentix** [comment]
Hi,

I have just commit a fix for include MSRP price in product import :)

**Comment by akkermanronald** [comment]
Fantastic! Many thanks!
