### ISSUE TITLE
Remote DB not supported ?

### ISSUE THREAD

**Issue by nbinnendijk** [Agence-DnD/PIMGento#95]
Hi, we recently changed our magento configuration. 
Previously the DB and Magento were on same server.

They are now on 2 separate servers, and we can not import anymore using PIMGento.

The error we have is:

"SQLSTATE[HY000]: General error: 13 Can't get stat of '/var/www/vhosts/domain.ch/httpdocs/var/import/pimgento_tmp/magento_export_categories_2.csv' (Errcode: 2)"

Is there something we should change in the configuration ?

Thx in advance

**Comment by magentix** [comment]
Hello,

The problem is "LOAD LOCAL DATA INFILE" query.

**LOAD DATA INFILE:** MySQL get file on MySQL server. If Apache is not on the same server than MySQL, you will get: "13 Can't get stat of '...' (Errcode: 2 - No such file or directory)"

**LOAD DATA LOCAL INFILE:** In this case, Apache and MySQL can be on different servers, but "local_infile" variable must be setted to "ON", otherwise you will get "1148 The used command is not allowed with this MySQL version"

In these 2 cases, MySQL user must have "FILE" rights

**Comment by magentix** [comment]
So, try to add "LOCAL" in query in "app/code/community/Pimgento/Core/Model/Resource/Request.php" :)
