### ISSUE TITLE
Error import enclosure

### ISSUE THREAD

**Issue by alexisfroger** [Agence-DnD/PIMGento#99]
Hey. 

I am on the Magento version 1.9.2.1 which works with Akeneo. I have a problem when I realize a Pimgento import. My enclosure file are quotes but Pimgento dosen't read it. For example if my field is "Magento category", Pimgento writes "Magento category" in the Database and not Magento category without quotes !

Can someone help on this issue?

Best Regards

Alexis

**Comment by clicktrend** [comment]
I had to change the handling of the CSV file (because I use an external db server like #95) to not use mysql's "local infile" (you can change this newly in the backend). So I face that the function "fgetcsv" ist not used correctly. The parameter for "enclosure" is set wrong however this setting is missing.

I will start a pull request. Maybe your problem will be solved, too.
